### ISSUE TITLE
verbose logging hangs when printing large file

### ISSUE THREAD

**Issue by aharbis** [IBM/dp-file-uploader#4]
Example of trying to log the XML request (when verbose logging is enabled) for a file that is very large (in this case a firmware image that's ~900 MB).

```
Generated XML:

^CTraceback (most recent call last):
  File "/usr/local/bin/dp-file-uploader", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/command_line.py", line 29, in main
    dp_file_uploader.run_with_args(args)
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/__init__.py", line 113, in run_with_args
    process_file(filename, directory, url, user, password)
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/__init__.py", line 84, in process_file
    xml = build_xml(directory, filename, data)
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/__init__.py", line 76, in build_xml
    print_pretty_xml(xmlRequest)
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/__init__.py", line 54, in print_pretty_xml
    dom = xml.dom.minidom.parseString(xml_str)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
  File "/private/tmp/python-20190709-71298-1cfqdlu/Python-3.7.4/Modules/pyexpat.c", line 282, in CharacterData
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 285, in character_data_handler_cdata
    value = node.data + data
KeyboardInterrupt
```

**Comment by aharbis** [comment]
Fixed in `v0.1.2`.
