### ISSUE TITLE
version.py sourced via relative file path, breaks when running outside repo dir

### ISSUE THREAD

**Issue by aharbis** [IBM/dp-file-uploader#6]
```
Traceback (most recent call last):
  File "/usr/local/bin/dp-file-uploader", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/command_line.py", line 28, in main
    args = process_args()
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/command_line.py", line 21, in process_args
    argparser.add_argument('-v', '--version', action='version', version=get_version())
  File "/usr/local/lib/python3.7/site-packages/dp_file_uploader/command_line.py", line 7, in get_version
    with open('./dp_file_uploader/version.py') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './dp_file_uploader/version.py'
```

**Comment by aharbis** [comment]
Fixed in `v0.1.2`.
